StoreFront.UI.MVC/Controllers/ActorsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using StoreFront.DATA.EF;

namespace StoreFront.UI.MVC.Controllers
{
    public class ActorsController : Controller
    {
        private StoreFrontEntities db = new StoreFrontEntities();

        // GET: Actors
        public ActionResult Index()
        {
            return View(db.Actors.ToList());
        }

        // GET: Actors/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Actor actor = db.Actors.Find(id);
            if (actor == null)
            {
                return HttpNotFound();
            }

            #region Movies
            var actorMovies = db.MovieTVActors.Where(m => m.ActorID == id).ToList();
            var movies = db.MoviesTVs.ToList();
            List<MoviesTV> credits = new List<MoviesTV>();
            foreach (var m in movies)
            {
                foreach (var am in actorMovies)
                {
                    if (m.MovieTVID == am.MovieTVID)
                    {
                        m.Character = am.Character;
                        credits.Add(m);
                    }
                }
            }
            ViewBag.Credits = credits;
            #endregion

            return View(actor);
        }

        // GET: Actors/Create
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Actors/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult Create([Bind(Include = "ActorID,FirstName,LastName,Country")] Actor actor)
        {
            if (ModelState.IsValid)
            {
                db.Actors.Add(actor);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(actor);
        }

        // GET: Actors/Edit/5
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Actor actor = db.Actors.Find(id);
            if (actor == null)
            {
                return HttpNotFound();
            }
            return View(actor);
        }

        // POST: Actors/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult Edit([Bind(Include = "ActorID,FirstName,LastName,Country")] Actor actor)
        {
            if (ModelState.IsValid)
            {
                db.Entry(actor).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(actor);
        }

        // GET: Actors/Delete/5
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Actor actor = db.Actors.Find(id);
            if (actor == null)
            {
                return HttpNotFound();
            }
            return View(actor);
        }

        // POST: Actors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult DeleteConfirmed(int id)
        {
            Actor actor = db.Actors.Find(id);
            db.Actors.Remove(actor);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        #region AJAX CRUD
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public JsonResult AjaxCreate(Actor actor)
        {
            db.Actors.Add(actor);
            db.SaveChanges();
            return Json(actor);
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public PartialViewResult ActorEdit(int id)
        {
            Actor actor = db.Actors.Find(id);
            return PartialView(actor);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public JsonResult AjaxEdit(Actor actor)
        {
            db.Entry(actor).State = EntityState.Modified;
            db.SaveChanges();
            return Json(actor);
        }

        [AcceptVerbs(HttpVerbs.Post)]
        [Authorize(Roles = "Admin")]
        public JsonResult AjaxDelete(int id)
        {
            Actor actor = db.Actors.Find(id);
            db.Actors.Remove(actor);
            db.SaveChanges();
            string confirmMessage = string.Format("Deleted actor '{0}' from database!", actor.FullName);
            return Json(new { id = id, message = confirmMessage });
        }
        #endregion

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

StoreFront.UI.MVC/Controllers/MoviesTVController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Drawing;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using StoreFront.DATA.EF;
using StoreFront.UI.MVC.Utilities; //gives us access to the ImageUploadUtility.cs
using StoreFront.UI.MVC.Models; //gives us access to the CartItemViewModel
using PagedList;

namespace StoreFront.UI.MVC.Controllers
{
    public class MoviesTVController : Controller
    {
        private StoreFrontEntities db = new StoreFrontEntities();

        // GET: MoviesTV
        public ActionResult Index(int? formatId, int? genreId, string searchString, string currentFilter, string sortOrder, string movieTVSort, int? page, int? PageSize)
        {
            //Session["filterState"] = new { formatId, genreId, searchString, currentFilter, sortOrder};
            List<MoviesTV> moviesTV = new List<MoviesTV>();
            ViewBag.CurrentSort = sortOrder;
            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }
            ViewBag.CurrentFilter = searchString;

            #region Dropdown List for Sorting
            ViewBag.movieTVSort = new List<SelectListItem>()
            {
                new SelectListItem { Text = "", Selected = true},
                new SelectListItem { Text = "Alphabetical: A-Z", Value = "AlphaAZ" },
                new SelectListItem { Text = "Alphabetical: Z-A", Value = "AlphaZA" },
                new SelectListItem { Text = "Price: Low to High", Value = "PriceAsc" },
                new SelectListItem { Text = "Price: High to Low", Value = "PriceDesc" },
            };
            switch (movieTVSort)
            {
                case "AlphaAZ":
                    moviesTV = db.MoviesTVs.Include(m => m.Genre).Include(m => m.Studio).Include(m => m.TitleStatus).Include(m => m.DiscType).Include(m => m.TitleType).Include(m => m.RegionCode).Include(m => m.MPAARating).OrderBy(s => s.Title).ToList();
                    break;
                case "AlphaZA":
                    moviesTV = db.MoviesTVs.Include(m => m.Genre).Include(m => m.Studio).Include(m => m.TitleStatus).Include(m => m.DiscType).Include(m => m.TitleType).Include(m => m.RegionCode).Include(m => m.MPAARating).OrderByDescending(s => s.Title).ToList();
                    break;
                case "PriceAsc":
                    moviesTV = db.MoviesTVs.Include(m => m.Genre).Include(m => m.Studio).Include(m => m.TitleStatus).Include(m => m.DiscType).Include(m => m.TitleType).Include(m => m.RegionCode).Include(m => m.MPAARating).OrderBy(s => s.Price).ToList();
                    break;
                case "PriceDesc":
                    moviesTV = db.MoviesTVs.Include(m => m.Genre).Include(m => m.Studio).Include(m => m.TitleStatus).Include(m => m.DiscType).Include(m => m.TitleType).Include(m => m.RegionCode).Include(m => m.MPAARating).OrderByDescending(s => s.Price).ToList();
                    break;
                default:
                    moviesTV = db.MoviesTVs.Include(m => m.Genre).Include(m => m.Studio).Include(m => m.TitleStatus).Include(m => m.DiscType).Include(m => m.TitleType).Include(m => m.RegionCode).Include(m => m.MPAARating).ToList();
                    break;
            }
            #endregion

            #region Filters
            ViewBag.Formats = db.DiscTypes.ToList();
            if (formatId != null)
            {
                moviesTV = db.MoviesTVs.Include(m => m.Genre).Include(m => m.Studio).Include(m => m.TitleStatus).Include(m => m.DiscType).Include(m => m.TitleType).Include(m => m.RegionCode).Include(m => m.MPAARating).Where(mtv => mtv.DiscTypeID == formatId).ToList();
            }

            ViewBag.Genres = db.Genres.ToList();
            if (genreId != null)
            {
                moviesTV = db.MoviesTVs.Include(m => m.Genre).Include(m => m.Studio).Include(m => m.TitleStatus).Include(m => m.DiscType).Include(m => m.TitleType).Include(m => m.RegionCode).Include(m => m.MPAARating).Where(mtv => mtv.GenreID == genreId).ToList();
            }
            #endregion

            #region Dropdown List for Page Size
            int count = db.MoviesTVs.Count();
            ViewBag.PageSize = new List<SelectListItem>()
            {
                new SelectListItem { Text = "3", Value = "3", Selected = true },
                new SelectListItem { Text = "6", Value = "6" },
                new SelectListItem { Text = "9", Value = "9" },
                new SelectListItem { Text = "12", Value = "12" },
                new SelectListItem { Text = "All", Value = count.ToString() }
            };
            int pageNumber = (page ?? 1);
            int pageSize = (PageSize ?? 3);
            ViewBag.psize = pageSize;
            #endregion

            #region Search
            if (!String.IsNullOrEmpty(searchString))
            {
                moviesTV = (
                    from m in moviesTV
                    where m.Title.ToLower().Contains(searchString.ToLower()) ||
                    m.Description.ToLower().Contains(searchString.ToLower()) ||
                    m.DiscType.DiscTypeName.ToLower().Contains(searchString.ToLower()) ||
                    m.DiscType.DiscTypeDescription.ToLower().Contains(searchString.ToLower()) ||
                    m.Genre.GenreName.ToLower().Contains(searchString.ToLower()) ||
                    m.Studio.StudioName.ToLower().Contains(searchString.ToLower()) ||
                    m.TitleType.TitleTypeName.ToLower().Contains(searchString.ToLower())
                    select m
                    ).ToList();
                ViewBag.SearchString = searchString;
            }
            #endregion

            return View(moviesTV.ToPagedList(pageNumber, pageSize));
        }

        // GET: MoviesTV/Details/5
        public ActionResult Details(int? id, int? formatId)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MoviesTV moviesTV = db.MoviesTVs.Find(id);
            if (moviesTV == null)
            {
                return HttpNotFound();
            }

            #region Actors
            var movieActors = db.MovieTVActors.Where(m => m.MovieTVID == id).ToList();
            var actors = db.Actors.ToList();
            List<Actor> cast = new List<Actor>();
            foreach (var a in actors)
            {
                foreach (var ma in movieActors)
                {
                    if (a.ActorID == ma.ActorID)
                    {
                        a.ActorOrder = ma.ActorOrder;
                        a.Character = ma.Character;
                        cast.Add(a);
                    }
                }
            }
            ViewBag.Cast = cast;
            #endregion

            #region Directors
            var movieDirectors = db.MovieTVDirectors.Where(m => m.MovieTVID == id).ToList();
            var directors = db.Directors.ToList();
            List<Director> directedBy = new List<Director>();
            foreach (var d in directors)
            {
                foreach (var md in movieDirectors)
                {
                    if (d.DirectorID == md.DirectorID)
                    {
                        d.DirectorOrder = md.DirectorOrder;
                        directedBy.Add(d);
                    }
                }
            }
            ViewBag.DirectedBy = directedBy;
            #endregion

            #region Writers
            var movieWriters = db.MovieTVWriters.Where(m => m.MovieTVID == id).ToList();
            var writers = db.Writers.ToList();
            List<Writer> writtenBy = new List<Writer>();
            foreach (var w in writers)
            {
                foreach (var mw in movieWriters)
                {
                    if (w.WriterID == mw.WriterID)
                    {
                        w.WriterOrder = mw.WriterOrder;
                        writtenBy.Add(w);
                    }
                }
            }
            ViewBag.WrittenBy = writtenBy;
            #endregion

            #region Related Products
            ViewBag.RelatedMoviesTVs = db.MoviesTVs.ToList();
            #endregion

            return View(moviesTV);
        }

        #region Custom Add-to-Cart functionality (called from the Details View)
        public ActionResult AddToCart(int qty, int movieTVID)
        {
            //We will use a Dictionary collection type to store items into the cart
            //Dictionaries store info as Key, Value pairs
            Dictionary<int, CartItemViewModel> shoppingCart = null;

            //check if the session variable called cart already exists - if it does we will use it to populate the local collection of shopping cart items we called shoppingCart
            if (Session["cart"] != null)
            {
                //session variable already exists and we will put items from it into our Dictionary called shoppingCart (local list of shopping cart items)
                shoppingCart = (Dictionary<int, CartItemViewModel>)Session["cart"];
                //when we UNBOX an object stored in Session to it's smaller more specific type we are using explicit casting
            }
            else
            {
                //if session cart doesn't exist yet, we need to instantiate it (aka NEW IT UP)
                shoppingCart = new Dictionary<int, CartItemViewModel>();
            }
            //after the if/else above we have a local version of the shopping cart list that is ready to have items added to it

            //find the product referenced by the ID that was passed to this method
            MoviesTV product = db.MoviesTVs.Where(m => m.MovieTVID == movieTVID).FirstOrDefault();
            if (product == null)
            {

StoreFront.UI.MVC/Views/Actors/ActorCreate.cshtml
@model StoreFront.DATA.EF.Actor

@using (Html.BeginForm("", "", FormMethod.Post, new { id = "ActorCreateForm" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <div class="col-md-3">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control", placeholder = "First Name" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>

            <div class="col-md-3">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control", placeholder = "Last Name" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>

            <div class="col-md-3">
                @Html.EditorFor(model => model.Country, new { htmlAttributes = new { @class = "form-control", placeholder = "Country" } })
                @Html.ValidationMessageFor(model => model.Country, "", new { @class = "text-danger" })
            </div>
            <div class="col-md-1">
                <input type="submit" value="Create" class="btn btn-danger" />
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

StoreFront.UI.MVC/Views/Actors/ActorEdit.cshtml
@model StoreFront.DATA.EF.Actor

@using (Html.BeginForm("AjaxEdit", "Actors", FormMethod.Post, new { id = "ActorEditForm" }))
{
    @Html.AntiForgeryToken()
    <table>
        <tr>
            @Html.HiddenFor(model => model.ActorID)
            <td>
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control", style = "width:275px; margin-left:-10px; margin-right:10px;" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </td>
            <td>
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control", style = "width:270px; margin-right:10px;" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </td>
            <td>
                @Html.EditorFor(model => model.Country, new { htmlAttributes = new { @class = "form-control", style = "width:260px; margin-right:10px;" } })
                @Html.ValidationMessageFor(model => model.Country, "", new { @class = "text-danger" })
            </td>
            <td>
                <input type="button" id="saveUpdate" value="Update Actor" class="btn btn-danger" />
            </td>
        </tr>
    </table>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

StoreFront.UI.MVC/Views/Actors/Create.cshtml
@model StoreFront.DATA.EF.Actor

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Actor</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Country, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Country, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Country, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

StoreFront.UI.MVC/Views/Actors/Details.cshtml
@model StoreFront.DATA.EF.Actor

@{
    ViewBag.Title = $"{Model.FullName}";
}

<!-- BREADCRUMB -->
<div id="breadcrumb" class="section">
    <!-- container -->
    <div class="container">
        <!-- row -->
        <div class="row">
            <div class="col-md-12">
                <ul class="breadcrumb-tree">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Movies/TV", "Index", "MoviesTV")</li>
                    <li>@Html.ActionLink("Actors", "Index", "Actors")</li>
                    <li class="active">@ViewBag.Title</li>
                </ul>
            </div>
        </div>
        <!-- /row -->
    </div>
    <!-- /container -->
</div>
<!-- /BREADCRUMB -->

<div class="section">
    <div class="container">
        <h2>@ViewBag.Title (@Model.Country)</h2>
        <hr />
        <div class="col-md-10 col-md-offset-1">
            <table class="table data-table table-striped" id="CreditsTable">
                <thead>
                    <tr>
                        <th>
                            Movie / Television Show
                        </th>
                        <th>
                            Character
                        </th>
                        <th>
                            Theatrical Release Date
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (StoreFront.DATA.EF.MoviesTV item in ViewBag.Credits)
                    {
                        <tr id="Movie-@item.MovieTVID">
                            <td>
                                <a href="@Url.Action("Details", "MoviesTV", new { id = item.MovieTVID })"><strong>@item.Title</strong></a>
                            </td>
                            <td>
                                @item.Character
                            </td>
                            <td>
                                @($"{item.ReleaseDate:d}")
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ActorID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

@section scripts{
    <script>
        $(document).ready(function () {
            $('#CreditsTable').DataTable({
                "order": [[ 2, "desc" ]],
                "info": false,
                "paging": false
            });
        });
    </script>
}

StoreFront.UI.MVC/Views/Actors/Index.cshtml
@model IEnumerable<StoreFront.DATA.EF.Actor>

@{
    ViewBag.Title = "Actors";
}

<!-- BREADCRUMB -->
<div id="breadcrumb" class="section">
    <!-- container -->
    <div class="container">
        <!-- row -->
        <div class="row">
            <div class="col-md-12">
                <ul class="breadcrumb-tree">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Movies/TV", "Index", "MoviesTV")</li>
                    <li class="active">@ViewBag.Title</li>
                </ul>
            </div>
        </div>
        <!-- /row -->
    </div>
    <!-- /container -->
</div>
<!-- /BREADCRUMB -->

<div class="section">
    <div class="container">
        <h2 class="text-center">@ViewBag.Title</h2>

        <p class="row">
            <button id="toggleActorCreate" class="btn btn-danger text-right pull-left">Add New</button>
        </p>
        <div id="ActorCreate">
            @Html.Partial("ActorCreate", new StoreFront.DATA.EF.Actor())
        </div>
        <table class="table data-table table-striped" id="ActorsTable">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.FirstName)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.LastName)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Country)
                    </th>
                    <th></th>
                </tr>
            </thead>

            <tbody>
                @foreach (var item in Model)
                {
                    <tr id="Actor-@item.ActorID">
                        <td>
                            <a href="@Url.Action("Details", "Actors", new { id = item.ActorID })"><strong>@item.FirstName</strong></a>
                        </td>
                        <td>
                            <a href="@Url.Action("Details", "Actors", new { id = item.ActorID })"><strong>@item.LastName</strong></a>
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Country)
                        </td>
                        <td>
                            <a href="" class="EditLink" id="@item.ActorID">Edit</a> |
                            @Ajax.ActionLink("Delete", "AjaxDelete", "Actors", new { id = item.ActorID },
                                new AjaxOptions {
                                    HttpMethod = "POST",
                                    Confirm = $"Are you sure you want to delete {item.FullName} from actors?",
                                    OnSuccess = "deleteConfirmed",
                                    OnFailure = "deleteFailed"
                                })
                        </td>
                    </tr>
                }
            </tbody>

        </table>
    </div>
</div>

@section scripts{
    <script>
        $(document).ready(function () {
            $(".data-table").DataTable({
                "order": [[1, "asc"]]
            });
        });

        //****** AJAX DELETE ******//
        function deleteConfirmed(response, status, data) {
            //remove the row from the table onscreen
            var rowId = "#Actor-" + response.id;
            $("#ActorsTable").find(rowId).remove();

            //display a status message (use AJAX response's message property)
            $("#MessageContent").html("<div class='alert alert-success'>" + response.message + "</div>");
        }
        function deleteFailed(response, status, data) {
            //display a status message
            $("#MessageContent").html("<div class='alert alert-danger'>Delete unsuccessful. Please try again.</div>");
        }

        //****** AJAX CREATE ******//
        $("#ActorCreate").hide(); //starts us out with the create form being hidden
        $("#toggleActorCreate").click(function () {
            $("#ActorCreate").toggle(); //flips the element between being shown or hidden from the user
        }); //end of click function

        $("#ActorCreateForm").submit(function (e) {
            var formData = $(this).serializeArray(); //serialization is the process of turning information in a certain language (C#) into a JSON format
            console.log(formData);
            e.preventDefault(); //keeps the default functionality (page reload) from happening
            $.ajax({
                url: "/Actors/AjaxCreate",
                type: "POST",
                data: formData,
                dataType: "json",
                error: function (e) {
                    $("#MessageContent").html("<div class='alert alert-danger'>There was a problem!</div>");
                },
                success: function (foo) {
                    $("#MessageContent").html("<div class='alert alert-success'>Record added!</div>");
                    $("#ActorCreateForm")[0].reset();
                    $(function () {
                        var row = '<tr><td>' + foo.FirstName + '</td>' +
                            '<td>' + foo.LastName + '</td>' +
                            '<td>' + foo.Country + '</td>' +
                            '<td>Refresh to view options</td></tr>';
                        $("#ActorsTable").append(row);
                    });
                }
            });
        });

        //****** AJAX EDIT ******
        var originalContent = null;
        $('a.EditLink').click(function (e) {
            e.preventDefault();
            var actorID = $(this).attr('id');
            var row = $("#Actor-" + actorID).children();
            originalContent = {
                ActorID: actorID,
                FirstName: row[0].innerText,
                LastName: row[1].innerText,
                Country: row[2].innerText,
            };
            console.log(originalContent);
            $.get("/Actors/ActorEdit/" + actorID,
                function (data) {
                    $("#Actor-" + actorID).replaceWith(
                        '<tr id="Actor-' + actorID + '"><td colspan="5">' + data + '</td></tr>'
                    );
                });
        });

        $(document).on("click", "#saveUpdate", function () {
            var formData = $("#ActorEditForm").serializeArray();

            $('#MessageContent').html("<div class='alert alert-info'>Please Wait...</div>");

            $.ajax({
                url: "/Actors/AjaxEdit",
                type: "POST",
                data: formData,
                dataType: "json",
                success: function (data) {
                    $('#MessageContent').html("<div class='alert alert-success'>Your Record was Successfully Updated!</div>");
                    $('#ActorEditForm')[0].reset();

                    $(function () {
                        var row = '<tr><td>' + data.FirstName +
                            '</td><td>' + data.LastName +
                            '</td><td>' + data.Country +
                            '</td><td>Refresh to view options</td></tr>';

                        $('#Actor-' + data.ActorID).replaceWith(row);
                    });
                },
                error: function (e) {
                    $('#MessageContent').html("<div class='alert alert-warning'>There was an error. Please try again or contact the site administrator.</div>");
                    $(function () {
                        var row = '<tr id="Actor-' + originalContent.ActorID + '"> <td>' + originalContent.FirstName +
                            '</td><td>' + originalContent.LastName +
                            '</td><td>' + originalContent.Country +
                            '</td><td>Refresh to view options</td></tr>';

                        $('#Actor-' + data.ActorID).replaceWith(row);
                    });
                }
            });
        });
    </script>
}