StoreFront.UI.MVC/Controllers/MovieTVActorsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using StoreFront.DATA.EF;

namespace StoreFront.UI.MVC.Controllers
{
    public class MovieTVActorsController : Controller
    {
        private StoreFrontEntities db = new StoreFrontEntities();

        // GET: MovieTVActors
        public ActionResult Index()
        {
            var movieTVActors = db.MovieTVActors.Include(m => m.Actor).Include(m => m.MoviesTV);
            return View(movieTVActors.ToList());
        }

        // GET: MovieTVActors/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MovieTVActor movieTVActor = db.MovieTVActors.Find(id);
            if (movieTVActor == null)
            {
                return HttpNotFound();
            }
            return View(movieTVActor);
        }

        // GET: MovieTVActors/Create
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            ViewBag.ActorID = new SelectList(db.Actors, "ActorID", "FullName");
            ViewBag.MovieTVID = new SelectList(db.MoviesTVs, "MovieTVID", "Title");
            return View();
        }

        // POST: MovieTVActors/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult Create([Bind(Include = "MovieTVActorID,MovieTVID,ActorID,ActorOrder,Character")] MovieTVActor movieTVActor)
        {
            if (ModelState.IsValid)
            {
                db.MovieTVActors.Add(movieTVActor);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ActorID = new SelectList(db.Actors, "ActorID", "FullName", movieTVActor.ActorID);
            ViewBag.MovieTVID = new SelectList(db.MoviesTVs, "MovieTVID", "Title", movieTVActor.MovieTVID);
            return View(movieTVActor);
        }

        // GET: MovieTVActors/Edit/5
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MovieTVActor movieTVActor = db.MovieTVActors.Find(id);
            if (movieTVActor == null)
            {
                return HttpNotFound();
            }
            ViewBag.ActorID = new SelectList(db.Actors, "ActorID", "FullName", movieTVActor.ActorID);
            ViewBag.MovieTVID = new SelectList(db.MoviesTVs, "MovieTVID", "Title", movieTVActor.MovieTVID);
            return View(movieTVActor);
        }

        // POST: MovieTVActors/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult Edit([Bind(Include = "MovieTVActorID,MovieTVID,ActorID,ActorOrder,Character")] MovieTVActor movieTVActor)
        {
            if (ModelState.IsValid)
            {
                db.Entry(movieTVActor).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ActorID = new SelectList(db.Actors, "ActorID", "FullName", movieTVActor.ActorID);
            ViewBag.MovieTVID = new SelectList(db.MoviesTVs, "MovieTVID", "Title", movieTVActor.MovieTVID);
            return View(movieTVActor);
        }

        // GET: MovieTVActors/Delete/5
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MovieTVActor movieTVActor = db.MovieTVActors.Find(id);
            if (movieTVActor == null)
            {
                return HttpNotFound();
            }
            return View(movieTVActor);
        }

        // POST: MovieTVActors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult DeleteConfirmed(int id)
        {
            MovieTVActor movieTVActor = db.MovieTVActors.Find(id);
            db.MovieTVActors.Remove(movieTVActor);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        //#region AJAX CRUD
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public JsonResult AjaxCreate(MovieTVActor movieTVActor)
        //{
        //    db.MovieTVActors.Add(movieTVActor);
        //    db.SaveChanges();
        //    ViewBag.ActorID = new SelectList(db.Actors, "ActorID", "FullName", movieTVActor.ActorID);
        //    ViewBag.MovieTVID = new SelectList(db.MoviesTVs, "MovieTVID", "Title", movieTVActor.MovieTVID);
        //    return Json(movieTVActor);
        //}

        //[HttpGet]
        //public PartialViewResult MovieTVActorEdit(int id)
        //{
        //    MovieTVActor movieTVActor = db.MovieTVActors.Find(id);
        //    return PartialView(movieTVActor);
        //}

        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public JsonResult AjaxEdit(MovieTVActor movieTVActor)
        //{
        //    db.Entry(movieTVActor).State = EntityState.Modified;
        //    db.SaveChanges();
        //    return Json(movieTVActor);
        //}

        //[AcceptVerbs(HttpVerbs.Post)]
        //public JsonResult AjaxDelete(int id)
        //{
        //    MovieTVActor movieTVActor = db.MovieTVActors.Find(id);
        //    db.MovieTVActors.Remove(movieTVActor);
        //    db.SaveChanges();
        //    string confirmMessage = string.Format("Deleted actor '{0}' from '{1}' database!", movieTVActor.Actor.FullName, movieTVActor.MoviesTV.Title);
        //    return Json(new { id = id, message = confirmMessage });
        //}
        //#endregion

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

StoreFront.UI.MVC/Controllers/MoviesTVController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Drawing;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using StoreFront.DATA.EF;
using StoreFront.UI.MVC.Utilities; //gives us access to the ImageUploadUtility.cs
using StoreFront.UI.MVC.Models; //gives us access to the CartItemViewModel
using PagedList;

namespace StoreFront.UI.MVC.Controllers
{
    public class MoviesTVController : Controller
    {
        private StoreFrontEntities db = new StoreFrontEntities();

        // GET: MoviesTV
        public ActionResult Index(int? formatId, int? genreId, string searchString, string currentFilter, string sortOrder, string movieTVSort, int? page, int? PageSize)
        {
            //Session["filterState"] = new { formatId, genreId, searchString, currentFilter, sortOrder};
            List<MoviesTV> moviesTV = new List<MoviesTV>();
            ViewBag.CurrentSort = sortOrder;
            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }
            ViewBag.CurrentFilter = searchString;

            #region Dropdown List for Sorting
            ViewBag.movieTVSort = new List<SelectListItem>()
            {
                new SelectListItem { Text = "", Selected = true},
                new SelectListItem { Text = "Alphabetical: A-Z", Value = "AlphaAZ" },
                new SelectListItem { Text = "Alphabetical: Z-A", Value = "AlphaZA" },
                new SelectListItem { Text = "Price: Low to High", Value = "PriceAsc" },
                new SelectListItem { Text = "Price: High to Low", Value = "PriceDesc" },
            };
            switch (movieTVSort)
            {
                case "AlphaAZ":
                    moviesTV = db.MoviesTVs.Include(m => m.Genre).Include(m => m.Studio).Include(m => m.TitleStatus).Include(m => m.DiscType).Include(m => m.TitleType).Include(m => m.RegionCode).Include(m => m.MPAARating).OrderBy(s => s.Title).ToList();
                    break;
                case "AlphaZA":
                    moviesTV = db.MoviesTVs.Include(m => m.Genre).Include(m => m.Studio).Include(m => m.TitleStatus).Include(m => m.DiscType).Include(m => m.TitleType).Include(m => m.RegionCode).Include(m => m.MPAARating).OrderByDescending(s => s.Title).ToList();
                    break;
                case "PriceAsc":
                    moviesTV = db.MoviesTVs.Include(m => m.Genre).Include(m => m.Studio).Include(m => m.TitleStatus).Include(m => m.DiscType).Include(m => m.TitleType).Include(m => m.RegionCode).Include(m => m.MPAARating).OrderBy(s => s.Price).ToList();
                    break;
                case "PriceDesc":
                    moviesTV = db.MoviesTVs.Include(m => m.Genre).Include(m => m.Studio).Include(m => m.TitleStatus).Include(m => m.DiscType).Include(m => m.TitleType).Include(m => m.RegionCode).Include(m => m.MPAARating).OrderByDescending(s => s.Price).ToList();
                    break;
                default:
                    moviesTV = db.MoviesTVs.Include(m => m.Genre).Include(m => m.Studio).Include(m => m.TitleStatus).Include(m => m.DiscType).Include(m => m.TitleType).Include(m => m.RegionCode).Include(m => m.MPAARating).ToList();
                    break;
            }
            #endregion

            #region Filters
            ViewBag.Formats = db.DiscTypes.ToList();
            if (formatId != null)
            {
                moviesTV = db.MoviesTVs.Include(m => m.Genre).Include(m => m.Studio).Include(m => m.TitleStatus).Include(m => m.DiscType).Include(m => m.TitleType).Include(m => m.RegionCode).Include(m => m.MPAARating).Where(mtv => mtv.DiscTypeID == formatId).ToList();
            }

            ViewBag.Genres = db.Genres.ToList();
            if (genreId != null)
            {
                moviesTV = db.MoviesTVs.Include(m => m.Genre).Include(m => m.Studio).Include(m => m.TitleStatus).Include(m => m.DiscType).Include(m => m.TitleType).Include(m => m.RegionCode).Include(m => m.MPAARating).Where(mtv => mtv.GenreID == genreId).ToList();
            }
            #endregion

            #region Dropdown List for Page Size
            int count = db.MoviesTVs.Count();
            ViewBag.PageSize = new List<SelectListItem>()
            {
                new SelectListItem { Text = "3", Value = "3", Selected = true },
                new SelectListItem { Text = "6", Value = "6" },
                new SelectListItem { Text = "9", Value = "9" },
                new SelectListItem { Text = "12", Value = "12" },
                new SelectListItem { Text = "All", Value = count.ToString() }
            };
            int pageNumber = (page ?? 1);
            int pageSize = (PageSize ?? 3);
            ViewBag.psize = pageSize;
            #endregion

            #region Search
            if (!String.IsNullOrEmpty(searchString))
            {
                moviesTV = (
                    from m in moviesTV
                    where m.Title.ToLower().Contains(searchString.ToLower()) ||
                    m.Description.ToLower().Contains(searchString.ToLower()) ||
                    m.DiscType.DiscTypeName.ToLower().Contains(searchString.ToLower()) ||
                    m.DiscType.DiscTypeDescription.ToLower().Contains(searchString.ToLower()) ||
                    m.Genre.GenreName.ToLower().Contains(searchString.ToLower()) ||
                    m.Studio.StudioName.ToLower().Contains(searchString.ToLower()) ||
                    m.TitleType.TitleTypeName.ToLower().Contains(searchString.ToLower())
                    select m
                    ).ToList();
                ViewBag.SearchString = searchString;
            }
            #endregion

            return View(moviesTV.ToPagedList(pageNumber, pageSize));
        }

        // GET: MoviesTV/Details/5
        public ActionResult Details(int? id, int? formatId)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MoviesTV moviesTV = db.MoviesTVs.Find(id);
            if (moviesTV == null)
            {
                return HttpNotFound();
            }

            #region Actors
            var movieActors = db.MovieTVActors.Where(m => m.MovieTVID == id).ToList();
            var actors = db.Actors.ToList();
            List<Actor> cast = new List<Actor>();
            foreach (var a in actors)
            {
                foreach (var ma in movieActors)
                {
                    if (a.ActorID == ma.ActorID)
                    {
                        a.ActorOrder = ma.ActorOrder;
                        a.Character = ma.Character;
                        cast.Add(a);
                    }
                }
            }
            ViewBag.Cast = cast;
            #endregion

            #region Directors
            var movieDirectors = db.MovieTVDirectors.Where(m => m.MovieTVID == id).ToList();
            var directors = db.Directors.ToList();
            List<Director> directedBy = new List<Director>();
            foreach (var d in directors)
            {
                foreach (var md in movieDirectors)
                {
                    if (d.DirectorID == md.DirectorID)
                    {
                        d.DirectorOrder = md.DirectorOrder;
                        directedBy.Add(d);
                    }
                }
            }
            ViewBag.DirectedBy = directedBy;
            #endregion

            #region Writers
            var movieWriters = db.MovieTVWriters.Where(m => m.MovieTVID == id).ToList();
            var writers = db.Writers.ToList();
            List<Writer> writtenBy = new List<Writer>();
            foreach (var w in writers)
            {
                foreach (var mw in movieWriters)
                {
                    if (w.WriterID == mw.WriterID)
                    {
                        w.WriterOrder = mw.WriterOrder;
                        writtenBy.Add(w);
                    }
                }
            }
            ViewBag.WrittenBy = writtenBy;
            #endregion

            #region Related Products
            ViewBag.RelatedMoviesTVs = db.MoviesTVs.ToList();
            #endregion

            return View(moviesTV);
        }

        #region Custom Add-to-Cart functionality (called from the Details View)
        public ActionResult AddToCart(int qty, int movieTVID)
        {
            //We will use a Dictionary collection type to store items into the cart
            //Dictionaries store info as Key, Value pairs
            Dictionary<int, CartItemViewModel> shoppingCart = null;

            //check if the session variable called cart already exists - if it does we will use it to populate the local collection of shopping cart items we called shoppingCart
            if (Session["cart"] != null)
            {
                //session variable already exists and we will put items from it into our Dictionary called shoppingCart (local list of shopping cart items)
                shoppingCart = (Dictionary<int, CartItemViewModel>)Session["cart"];
                //when we UNBOX an object stored in Session to it's smaller more specific type we are using explicit casting
            }
            else
            {
                //if session cart doesn't exist yet, we need to instantiate it (aka NEW IT UP)
                shoppingCart = new Dictionary<int, CartItemViewModel>();
            }
            //after the if/else above we have a local version of the shopping cart list that is ready to have items added to it

            //find the product referenced by the ID that was passed to this method
            MoviesTV product = db.MoviesTVs.Where(m => m.MovieTVID == movieTVID).FirstOrDefault();
            if (product == null)
            {

StoreFront.UI.MVC/Views/MovieTVActors/Create.cshtml
@model StoreFront.DATA.EF.MovieTVActor

@{
    ViewBag.Title = "Create";
}

<div class="container">
    <h2>Create</h2>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>MovieTVActor</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.MovieTVID, "Movie/TV Title", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("MovieTVID", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.MovieTVID, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.ActorID, "Actor", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("ActorID", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.ActorID, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.ActorOrder, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ActorOrder, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ActorOrder, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Character, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Character, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Character, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

StoreFront.UI.MVC/Views/MovieTVActors/Delete.cshtml
@model StoreFront.DATA.EF.MovieTVActor

@{
    ViewBag.Title = "Delete";
}

<div class="container">
    <h2>Delete</h2>

    <h3>Are you sure you want to delete this?</h3>
    <div>
        <h4>MovieTVActor</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.MoviesTV.Title)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.MoviesTV.Title)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Actor.FullName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Actor.FullName)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Character)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Character)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.ActorOrder)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.ActorOrder)
            </dd>

        </dl>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-default" /> |
                @Html.ActionLink("Back to List", "Index")
            </div>
        }
    </div>
</div>

StoreFront.UI.MVC/Views/MovieTVActors/Index.cshtml
@model IEnumerable<StoreFront.DATA.EF.MovieTVActor>

@{
    ViewBag.Title = "Movie/TV Actor Index";
}

<!-- BREADCRUMB -->
<div id="breadcrumb" class="section">
    <!-- container -->
    <div class="container">
        <!-- row -->
        <div class="row">
            <div class="col-md-12">
                <ul class="breadcrumb-tree">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Movies/TV", "Index", "MoviesTV")</li>
                    <li>@Html.ActionLink("Actors", "Index", "Actors")</li>
                    <li class="active">@ViewBag.Title</li>
                </ul>
            </div>
        </div>
        <!-- /row -->
    </div>
    <!-- /container -->
</div>
<!-- /BREADCRUMB -->

<div class="section">
    <div class="container">
        <h2 class="text-center">@ViewBag.Title</h2>

        <p class="row">
            @Html.ActionLink("Add New", "Create", null, new { @class = "btn btn-danger text-right pull-left" })
        </p>
        @*<p class="row">
                <button id="toggleMovieTVActorCreate" class="btn btn-danger text-right pull-left">Add New</button>
            </p>
            <div id="MovieTVActorCreate">
                @Html.Partial("MovieTVActorCreate", new StoreFront.DATA.EF.MovieTVActor())
            </div>*@
        <table class="table data-table table-striped" id="MovieTVActorsTable">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.MoviesTV.Title)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Actor.FullName)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.ActorOrder)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Character)
                    </th>
                    <th></th>
                </tr>
            </thead>

            <tbody>
                @foreach (var item in Model)
                {
                    <tr id="MovieTVActor-@item.MovieTVActorID">
                        <td>
                            <a href="@Url.Action("Details", "MoviesTV", new { id = item.MovieTVID })"><strong>@item.MoviesTV.Title</strong></a>
                        </td>
                        <td>
                            <a href="@Url.Action("Details", "Actors", new { id = item.ActorID })"><strong>@item.Actor.FullName</strong></a>
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.ActorOrder)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Character)
                        </td>
                        <td>
                            @Html.ActionLink("Edit", "Edit", new { id = item.MovieTVActorID }) |
                            @Html.ActionLink("Delete", "Delete", new { id = item.MovieTVActorID })
                            @*<a href="" class="EditLink" id="@item.MovieTVActorID">Edit</a> |
                                @Ajax.ActionLink("Delete", "AjaxDelete", "MovieTVActors", new { id = item.MovieTVActorID },
                                    new AjaxOptions {
                                        HttpMethod = "POST",
                                        Confirm = $"Are you sure you want to delete {item.Actor.FullName} from {item.MoviesTV.Title}?",
                                        OnSuccess = "deleteConfirmed",
                                        OnFailure = "deleteFailed"
                                    })*@
                        </td>
                    </tr>
                }
            </tbody>

        </table>
    </div>
</div>

@section scripts{
    <script>
        $(document).ready(function () {
            $(".data-table").DataTable({
                "order": [[0, "asc"]]
            });
        });

        //****** AJAX DELETE ******//
        function deleteConfirmed(response, status, data) {
            //remove the row from the table onscreen
            var rowId = "#MovieTVActor-" + response.id;
            $("#MovieTVActorsTable").find(rowId).remove();

            //display a status message (use AJAX response's message property)
            $("#MessageContent").html("<div class='alert alert-success'>" + response.message + "</div>");
        }
        function deleteFailed(response, status, data) {
            //display a status message
            $("#MessageContent").html("<div class='alert alert-danger'>Delete unsuccessful. Please try again.</div>");
        }

        //****** AJAX CREATE ******//
        $("#MovieTVActorCreate").hide(); //starts us out with the create form being hidden
        $("#toggleMovieTVActorCreate").click(function () {
            $("#MovieTVActorCreate").toggle(); //flips the element between being shown or hidden from the user
        }); //end of click function

        $("#MovieTVActorCreateForm").submit(function (e) {
            var formData = $(this).serializeArray(); //serialization is the process of turning information in a certain language (C#) into a JSON format
            console.log(formData);
            e.preventDefault(); //keeps the default functionality (page reload) from happening
            $.ajax({
                url: "/MovieTVActors/AjaxCreate",
                type: "POST",
                data: formData,
                dataType: "json",
                error: function (e) {
                    $("#MessageContent").html("<div class='alert alert-danger'>There was a problem!</div>");
                },
                success: function (foo) {
                    $("#MessageContent").html("<div class='alert alert-success'>Record added!</div>");
                    $("#MovieTVActorCreateForm")[0].reset();
                    $(function () {
                        var row = '<tr><td>' + foo.MoviesTV.Title + '</td>' +
                            '<td>' + foo.Actor.FullName + '</td>' +
                            '<td>' + foo.ActorOrder + '</td>' +
                            '<td>' + foo.Character + '</td>' +
                            '<td>Refresh to view options</td></tr>';
                        $("#MovieTVActorsTable").append(row);
                    });
                }
            });
        });

        //****** AJAX EDIT ******
        var originalContent = null;
        $('a.EditLink').click(function (e) {
            e.preventDefault();
            var movieTVActorID = $(this).attr('id');
            var row = $("#MovieTVActor-" + movieTVActorID).children();
            originalContent = {
                MovieTVActorID: movieTVActorID,
                Title: row[0].innerText,
                FullName: row[1].innerText,
                ActorOrder: row[2].innerText,
                Character: row[3].innerText,
            };
            console.log(originalContent);
            $.get("/MovieTVActors/MovieTVActorEdit/" + movieTVActorID,
                function (data) {
                    $("#MovieTVActor-" + movieTVActorID).replaceWith(
                        '<tr id="MovieTVActor-' + movieTVActorID + '"><td colspan="5">' + data + '</td></tr>'
                    );
                });
        });

        $(document).on("click", "#saveUpdate", function () {
            var formData = $("#MovieTVActorEditForm").serializeArray();

            $('#MessageContent').html("<div class='alert alert-info'>Please Wait...</div>");

            $.ajax({
                url: "/MovieTVActors/AjaxEdit",
                type: "POST",
                data: formData,
                dataType: "json",
                success: function (data) {
                    $('#MessageContent').html("<div class='alert alert-success'>Your Record was Successfully Updated!</div>");
                    $('#MovieTVActorEditForm')[0].reset();

                    $(function () {
                        var row = '<tr><td>' + data.Title +
                            '</td><td>' + data.FullName +
                            '</td><td>' + data.ActorOrder +
                            '</td><td>' + data.Character +
                            '</td><td>Refresh to view options</td></tr>';

                        $('#MovieTVActor-' + data.MovieTVActorID).replaceWith(row);
                    });
                },
                error: function (e) {
                    $('#MessageContent').html("<div class='alert alert-warning'>There was an error. Please try again or contact the site administrator.</div>");
                    $(function () {
                        var row = '<tr id="MovieTVActor-' + originalContent.MovieTVActorID + '"> <td>' + originalContent.Title +
                            '</td><td>' + originalContent.FullName +
                            '</td><td>' + originalContent.ActorOrder +
                            '</td><td>' + originalContent.Character +
                            '</td><td>Refresh to view options</td></tr>';

                        $('#MovieTVActor-' + data.MovieTVActorID).replaceWith(row);
                    });
                }
            });
        });
    </script>
}

StoreFront.UI.MVC/Views/MovieTVActors/MovieTVActorEdit.cshtml
@*@model StoreFront.DATA.EF.MovieTVActor

@using (Html.BeginForm("AjaxEdit", "MovieTVActors", FormMethod.Post, new { id = "MovieTVActorEditForm" }))
{
    @Html.AntiForgeryToken()
    <table>
        <tr>
            @Html.HiddenFor(model => model.MovieTVActorID)
            <td>
                @Html.DropDownList("MovieTVID", null, htmlAttributes: new { @class = "form-control", style = "width:275px; margin-left:-10px; margin-right:10px;" })
                @Html.ValidationMessageFor(model => model.MovieTVID, "", new { @class = "text-danger" })
            </td>
            <td>
                @Html.DropDownList("ActorID", null, htmlAttributes: new { htmlAttributes = new { @class = "form-control", style = "width:270px; margin-right:10px;" })
                @Html.ValidationMessageFor(model => model.ActorID, "", new { @class = "text-danger" })
            </td>
            <td>
                @Html.EditorFor(model => model.ActorOrder, new { htmlAttributes = new { @class = "form-control", style = "width:260px; margin-right:10px;" } })
                @Html.ValidationMessageFor(model => model.ActorOrder, "", new { @class = "text-danger" })
            </td>
            <td>
                @Html.EditorFor(model => model.Character, new { htmlAttributes = new { @class = "form-control", style = "width:260px; margin-right:10px;" } })
                @Html.ValidationMessageFor(model => model.Character, "", new { @class = "text-danger" })
            </td>
            <td>
                <input type="button" id="saveUpdate" value="Update Movie/TV Actor" class="btn btn-danger" />
            </td>
        </tr>
    </table>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}*@