StoreFront.UI.MVC/Controllers/MoviesTVController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Drawing;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using StoreFront.DATA.EF;
using StoreFront.UI.MVC.Utilities; //gives us access to the ImageUploadUtility.cs
using StoreFront.UI.MVC.Models; //gives us access to the CartItemViewModel
using PagedList;

namespace StoreFront.UI.MVC.Controllers
{
    public class MoviesTVController : Controller
    {
        private StoreFrontEntities db = new StoreFrontEntities();

        // GET: MoviesTV
        public ActionResult Index(int? formatId, int? genreId, string searchString, string currentFilter, string sortOrder, string movieTVSort, int? page, int? PageSize)
        {
            //Session["filterState"] = new { formatId, genreId, searchString, currentFilter, sortOrder};
            List<MoviesTV> moviesTV = new List<MoviesTV>();
            ViewBag.CurrentSort = sortOrder;
            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }
            ViewBag.CurrentFilter = searchString;

            #region Dropdown List for Sorting
            ViewBag.movieTVSort = new List<SelectListItem>()
            {
                new SelectListItem { Text = "", Selected = true},
                new SelectListItem { Text = "Alphabetical: A-Z", Value = "AlphaAZ" },
                new SelectListItem { Text = "Alphabetical: Z-A", Value = "AlphaZA" },
                new SelectListItem { Text = "Price: Low to High", Value = "PriceAsc" },
                new SelectListItem { Text = "Price: High to Low", Value = "PriceDesc" },
            };
            switch (movieTVSort)
            {
                case "AlphaAZ":
                    moviesTV = db.MoviesTVs.Include(m => m.Genre).Include(m => m.Studio).Include(m => m.TitleStatus).Include(m => m.DiscType).Include(m => m.TitleType).Include(m => m.RegionCode).Include(m => m.MPAARating).OrderBy(s => s.Title).ToList();
                    break;
                case "AlphaZA":
                    moviesTV = db.MoviesTVs.Include(m => m.Genre).Include(m => m.Studio).Include(m => m.TitleStatus).Include(m => m.DiscType).Include(m => m.TitleType).Include(m => m.RegionCode).Include(m => m.MPAARating).OrderByDescending(s => s.Title).ToList();
                    break;
                case "PriceAsc":
                    moviesTV = db.MoviesTVs.Include(m => m.Genre).Include(m => m.Studio).Include(m => m.TitleStatus).Include(m => m.DiscType).Include(m => m.TitleType).Include(m => m.RegionCode).Include(m => m.MPAARating).OrderBy(s => s.Price).ToList();
                    break;
                case "PriceDesc":
                    moviesTV = db.MoviesTVs.Include(m => m.Genre).Include(m => m.Studio).Include(m => m.TitleStatus).Include(m => m.DiscType).Include(m => m.TitleType).Include(m => m.RegionCode).Include(m => m.MPAARating).OrderByDescending(s => s.Price).ToList();
                    break;
                default:
                    moviesTV = db.MoviesTVs.Include(m => m.Genre).Include(m => m.Studio).Include(m => m.TitleStatus).Include(m => m.DiscType).Include(m => m.TitleType).Include(m => m.RegionCode).Include(m => m.MPAARating).ToList();
                    break;
            }
            #endregion

            #region Filters
            ViewBag.Formats = db.DiscTypes.ToList();
            if (formatId != null)
            {
                moviesTV = db.MoviesTVs.Include(m => m.Genre).Include(m => m.Studio).Include(m => m.TitleStatus).Include(m => m.DiscType).Include(m => m.TitleType).Include(m => m.RegionCode).Include(m => m.MPAARating).Where(mtv => mtv.DiscTypeID == formatId).ToList();
            }

            ViewBag.Genres = db.Genres.ToList();
            if (genreId != null)
            {
                moviesTV = db.MoviesTVs.Include(m => m.Genre).Include(m => m.Studio).Include(m => m.TitleStatus).Include(m => m.DiscType).Include(m => m.TitleType).Include(m => m.RegionCode).Include(m => m.MPAARating).Where(mtv => mtv.GenreID == genreId).ToList();
            }
            #endregion

            #region Dropdown List for Page Size
            int count = db.MoviesTVs.Count();
            ViewBag.PageSize = new List<SelectListItem>()
            {
                new SelectListItem { Text = "3", Value = "3", Selected = true },
                new SelectListItem { Text = "6", Value = "6" },
                new SelectListItem { Text = "9", Value = "9" },
                new SelectListItem { Text = "12", Value = "12" },
                new SelectListItem { Text = "All", Value = count.ToString() }
            };
            int pageNumber = (page ?? 1);
            int pageSize = (PageSize ?? 3);
            ViewBag.psize = pageSize;
            #endregion

            #region Search
            if (!String.IsNullOrEmpty(searchString))
            {
                moviesTV = (
                    from m in moviesTV
                    where m.Title.ToLower().Contains(searchString.ToLower()) ||
                    m.Description.ToLower().Contains(searchString.ToLower()) ||
                    m.DiscType.DiscTypeName.ToLower().Contains(searchString.ToLower()) ||
                    m.DiscType.DiscTypeDescription.ToLower().Contains(searchString.ToLower()) ||
                    m.Genre.GenreName.ToLower().Contains(searchString.ToLower()) ||
                    m.Studio.StudioName.ToLower().Contains(searchString.ToLower()) ||
                    m.TitleType.TitleTypeName.ToLower().Contains(searchString.ToLower())
                    select m
                    ).ToList();
                ViewBag.SearchString = searchString;
            }
            #endregion

            return View(moviesTV.ToPagedList(pageNumber, pageSize));
        }

        // GET: MoviesTV/Details/5
        public ActionResult Details(int? id, int? formatId)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MoviesTV moviesTV = db.MoviesTVs.Find(id);
            if (moviesTV == null)
            {
                return HttpNotFound();
            }

            #region Actors
            var movieActors = db.MovieTVActors.Where(m => m.MovieTVID == id).ToList();
            var actors = db.Actors.ToList();
            List<Actor> cast = new List<Actor>();
            foreach (var a in actors)
            {
                foreach (var ma in movieActors)
                {
                    if (a.ActorID == ma.ActorID)
                    {
                        a.ActorOrder = ma.ActorOrder;
                        a.Character = ma.Character;
                        cast.Add(a);
                    }
                }
            }
            ViewBag.Cast = cast;
            #endregion

            #region Directors
            var movieDirectors = db.MovieTVDirectors.Where(m => m.MovieTVID == id).ToList();
            var directors = db.Directors.ToList();
            List<Director> directedBy = new List<Director>();
            foreach (var d in directors)
            {
                foreach (var md in movieDirectors)
                {
                    if (d.DirectorID == md.DirectorID)
                    {
                        d.DirectorOrder = md.DirectorOrder;
                        directedBy.Add(d);
                    }
                }
            }
            ViewBag.DirectedBy = directedBy;
            #endregion

            #region Writers
            var movieWriters = db.MovieTVWriters.Where(m => m.MovieTVID == id).ToList();
            var writers = db.Writers.ToList();
            List<Writer> writtenBy = new List<Writer>();
            foreach (var w in writers)
            {
                foreach (var mw in movieWriters)
                {
                    if (w.WriterID == mw.WriterID)
                    {
                        w.WriterOrder = mw.WriterOrder;
                        writtenBy.Add(w);
                    }
                }
            }
            ViewBag.WrittenBy = writtenBy;
            #endregion

            #region Related Products
            ViewBag.RelatedMoviesTVs = db.MoviesTVs.ToList();
            #endregion

            return View(moviesTV);
        }

        #region Custom Add-to-Cart functionality (called from the Details View)
        public ActionResult AddToCart(int qty, int movieTVID)
        {
            //We will use a Dictionary collection type to store items into the cart
            //Dictionaries store info as Key, Value pairs
            Dictionary<int, CartItemViewModel> shoppingCart = null;

            //check if the session variable called cart already exists - if it does we will use it to populate the local collection of shopping cart items we called shoppingCart
            if (Session["cart"] != null)
            {
                //session variable already exists and we will put items from it into our Dictionary called shoppingCart (local list of shopping cart items)
                shoppingCart = (Dictionary<int, CartItemViewModel>)Session["cart"];
                //when we UNBOX an object stored in Session to it's smaller more specific type we are using explicit casting
            }
            else
            {
                //if session cart doesn't exist yet, we need to instantiate it (aka NEW IT UP)
                shoppingCart = new Dictionary<int, CartItemViewModel>();
            }
            //after the if/else above we have a local version of the shopping cart list that is ready to have items added to it

            //find the product referenced by the ID that was passed to this method
            MoviesTV product = db.MoviesTVs.Where(m => m.MovieTVID == movieTVID).FirstOrDefault();
            if (product == null)
            {

StoreFront.UI.MVC/Controllers/ShoppingCartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using StoreFront.UI.MVC.Models;

namespace StoreFront.UI.MVC.Controllers
{
    public class ShoppingCartController : Controller
    {
        // GET: ShoppingCart
        public ActionResult Index()
        {
            //pull in session based cart into a local variable that we can pass to the view
            var shoppingCart = (Dictionary<int, CartItemViewModel>)Session["cart"];
            if (shoppingCart == null || shoppingCart.Count == 0)
            {
                //user either hasn't put anything in the cart or removed all the items, or session has expired
                //set cart to an empty object (can still send that to the view, unlike NULL)
                shoppingCart = new Dictionary<int, CartItemViewModel>();

                //create a message about the empty shopping cart
                ViewBag.Message = "There are no items in your cart.";
            }
            else
            {
                ViewBag.Message = null; //explicitly clearing out the value in Message
            }
            return View(shoppingCart);
        }

        public ActionResult RemoveFromCart(int id)
        {
            //get the cart out of session and into a local variable
            Dictionary<int, CartItemViewModel> shoppingCart = (Dictionary<int, CartItemViewModel>)Session["cart"];

            //remove the item from the local shoppingCart
            shoppingCart.Remove(id);

            //set up ViewBag message if no items are in the cart
            //if (shoppingCart.Count == 0)
            //{
            //    ViewBag.Message = "You've removed all items from your cart.";
            //}
            //The code above will not yield a message on the view. The Index ActionResult overwrites the ViewBag.Message. If you wanted to pass a message about removing all items then you would need to make a different ViewBag variable
            //if (shoppingCart.Count == 0)
            //{
            //    ViewBag.RemoveMessage = "You've removed all items from your cart.";
            //}

            //return the local shopping cart to the session and send the user back to the ShoppingCart Index
            Session["cart"] = shoppingCart;
            return RedirectToAction("Index");
        }

        public ActionResult UpdateCart(int movieTVID, int qty)
        {
            //get the cart out of session and into a local variable
            Dictionary<int, CartItemViewModel> shoppingCart = (Dictionary<int, CartItemViewModel>)Session["cart"];

            //target the correct cart item using the movieTVID key then change the Qty property using the qty parameter
            shoppingCart[movieTVID].Qty = qty;

            //return the local shopping cart to the session and send the user back to the ShoppingCart Index
            Session["cart"] = shoppingCart;
            return RedirectToAction("Index");
        }

        public ActionResult Checkout()
        {
            //pull in session based cart into a local variable that we can pass to the view
            var shoppingCart = (Dictionary<int, CartItemViewModel>)Session["cart"];
            if (shoppingCart == null || shoppingCart.Count == 0)
            {
                //user either hasn't put anything in the cart or removed all the items, or session has expired
                //set cart to an empty object (can still send that to the view, unlike NULL)
                shoppingCart = new Dictionary<int, CartItemViewModel>();

                //create a message about the empty shopping cart
                ViewBag.Message = "There are no items in your cart.";
            }
            else
            {
                ViewBag.Message = null; //explicitly clearing out the value in Message
            }
            return View(shoppingCart);
        }
    }
}

StoreFront.UI.MVC/Views/ShoppingCart/Checkout.cshtml
@model Dictionary<int, StoreFront.UI.MVC.Models.CartItemViewModel>
@{
    ViewBag.Title = "Checkout";

    //add a couple of local variables for calculations later on in the page
    decimal? cartTotal = 0;
    int totalCountOfItems = 0;
}

<!-- BREADCRUMB -->
<div id="breadcrumb" class="section">
    <!-- container -->
    <div class="container">
        <!-- row -->
        <div class="row">
            <div class="col-md-12">
                <ul class="breadcrumb-tree">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li class="active">@ViewBag.Title</li>
                </ul>
            </div>
        </div>
        <!-- /row -->
    </div>
    <!-- /container -->
</div>
<!-- /BREADCRUMB -->
<!-- SECTION -->
<div class="section">
    <!-- container -->
    <div class="container">
        <h2 class="col-md-offset-4 col-md-4 text-center">@ViewBag.Title</h2>
        <div class="col-md-4 text-right" style="padding-bottom: 60px">
            @Html.ActionLink("Back to Shopping", "Index", "MoviesTV", null, new { @class = "primary-btn cta-btn" })
        </div>
        <!-- row -->
        <div class="row">
            <div class="col-md-7">
                <!-- Billing Details -->
                <div class="billing-details">
                    <div class="section-title">
                        <h3 class="title">Billing address</h3>
                    </div>
                    <div class="form-group">
                        <input class="input" type="text" name="first-name" placeholder="First Name">
                    </div>
                    <div class="form-group">
                        <input class="input" type="text" name="last-name" placeholder="Last Name">
                    </div>
                    <div class="form-group">
                        <input class="input" type="email" name="email" placeholder="Email">
                    </div>
                    <div class="form-group">
                        <input class="input" type="text" name="address" placeholder="Address">
                    </div>
                    <div class="form-group">
                        <input class="input" type="text" name="city" placeholder="City">
                    </div>
                    <div class="form-group">
                        <input class="input" type="text" name="state" placeholder="State">
                    </div>
                    <div class="form-group">
                        <input class="input" type="text" name="zip-code" placeholder="ZIP Code">
                    </div>
                    <div class="form-group">
                        <input class="input" type="tel" name="tel" placeholder="Telephone">
                    </div>
                    <div class="form-group">
                        <div class="input-checkbox">
                            <input type="checkbox" id="create-account">
                            <label for="create-account">
                                <span></span>
                                Create Account?
                            </label>
                            <div class="caption">
                                <p>To create an account, please enter a password for your account.</p>
                                <input class="input" type="password" name="password" placeholder="Enter Your Password">
                            </div>
                        </div>
                    </div>
                </div>
                <!-- /Billing Details -->
                <!-- Shipping Details -->
                <div class="shipping-details">
                    <div class="section-title">
                        <h3 class="title">Shipping address</h3>
                    </div>
                    <div class="input-checkbox">
                        <input type="checkbox" id="shipping-address">
                        <label for="shipping-address">
                            <span></span>
                            Ship to a different address?
                        </label>
                        <div class="caption">
                            <div class="form-group">
                                <input class="input" type="text" name="first-name" placeholder="First Name">
                            </div>
                            <div class="form-group">
                                <input class="input" type="text" name="last-name" placeholder="Last Name">
                            </div>
                            <div class="form-group">
                                <input class="input" type="email" name="email" placeholder="Email">
                            </div>
                            <div class="form-group">
                                <input class="input" type="text" name="address" placeholder="Address">
                            </div>
                            <div class="form-group">
                                <input class="input" type="text" name="city" placeholder="City">
                            </div>
                            <div class="form-group">
                                <input class="input" type="text" name="state" placeholder="State">
                            </div>
                            <div class="form-group">
                                <input class="input" type="text" name="zip-code" placeholder="ZIP Code">
                            </div>
                            <div class="form-group">
                                <input class="input" type="tel" name="tel" placeholder="Telephone">
                            </div>
                        </div>
                    </div>
                </div>
                <!-- /Shipping Details -->
                <!-- Order notes -->
                <div class="order-notes">
                    <textarea class="input" placeholder="Order Notes"></textarea>
                </div>
                <!-- /Order notes -->
            </div>
            <!-- Order Details -->
            <div class="col-md-5 order-details">
                <div class="section-title text-center">
                    <h3 class="title">Your Order</h3>
                </div>
                <div class="order-summary">
                    <div class="order-col">
                        <div><strong>PRODUCT</strong></div>
                        <div><strong>TOTAL</strong></div>
                    </div>
                    <div class="order-products">
                        @if (Model.Count == 0)
                        {
                            <p class="alert alert-danger">
                                @*@if (ViewBag.RemoveMessage != null)
                                {
                                    ViewBag.RemoveMessage
                                }*@
                                @ViewBag.Message
                            </p>
                        }
                        else
                        {
                            foreach (var item in Model)
                            {
                                <div class="order-col">
                                    <div>@item.Value.Qty @item.Value.Product.Title</div>
                                    <div>
                                        @* calculate lineTotal & update the running total variable for each row *@
                                    @{
                                        decimal? lineTotal = item.Value.Product.Price * item.Value.Qty;
                                        cartTotal += lineTotal;
                                    }
                                    @string.Format($"{lineTotal:c}")
                                </div>
                            </div>
                        }
                    }
                    </div>
                    <div class="order-col">
                        <div>Shipping</div>
                        <div><strong>FREE</strong></div>
                    </div>
                    <div class="order-col">
                        <div><strong>TOTAL</strong></div>
                        <div><strong class="order-total">@string.Format($"{cartTotal:c}")</strong></div>
                    </div>
                </div>
                <div class="payment-method">
                    <div class="input-radio">
                        <input type="radio" name="payment" id="payment-1">
                        <label for="payment-1">
                            <span></span>
                            Credit/Debit Card
                        </label>
                        <div class="caption">
                            <div class="form-group">
                                <input class="input" type="text" name="card" placeholder="Card Number">
                            </div>
                        </div>
                    </div>
                    <div class="input-radio">
                        <input type="radio" name="payment" id="payment-2">
                        <label for="payment-2">
                            <span></span>
                            Bank Account
                        </label>
                        <div class="caption">
                            <div class="form-group">
                                <input class="input" type="text" name="bank" placeholder="Bank Account Number">
                            </div>
                        </div>
                    </div>
                    <div class="input-radio">
                        <input type="radio" name="payment" id="payment-3">
                        <label for="payment-3">
                            <span></span>
                            Paypal
                        </label>
                        <div class="caption">
                            <div class="form-group">
                                <input class="input" type="text" name="paypal" placeholder="Paypal Account">
                            </div>
                        </div>
                    </div>
                </div>
                <div class="input-checkbox">
                    <input type="checkbox" id="terms">
                    <label for="terms">
                        <span></span>
                        I've read and accept the <a href="#">terms & conditions</a>
                    </label>
                </div>
                <a href="#" class="primary-btn order-submit">Place order</a>
            </div>
            <!-- /Order Details -->
        </div>
        <!-- /row -->
    </div>
    <!-- /container -->
</div>
<!-- /SECTION -->

StoreFront.UI.MVC/Views/ShoppingCart/Index.cshtml
@model Dictionary<int, StoreFront.UI.MVC.Models.CartItemViewModel>
@{
    ViewBag.Title = "Shopping Cart";

    //add a couple of local variables for calculations later on in the page
    decimal? cartTotal = 0;
    int totalCountOfItems = 0;
}

<!-- BREADCRUMB -->
<div id="breadcrumb" class="section">
    <!-- container -->
    <div class="container">
        <!-- row -->
        <div class="row">
            <div class="col-md-12">
                <ul class="breadcrumb-tree">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li class="active">@ViewBag.Title</li>
                </ul>
            </div>
        </div>
        <!-- /row -->
    </div>
    <!-- /container -->
</div>
<!-- /BREADCRUMB -->
<!-- SECTION -->
<div class="section">
    <!-- container -->
    <div class="container">
        <h2 class="col-md-offset-4 col-md-4 text-center">@ViewBag.Title</h2>
        <div class="col-md-4 text-right" style="padding-bottom: 60px">
            @Html.ActionLink("Back to Shopping", "Index", "MoviesTV", null, new { @class = "primary-btn cta-btn" })
        </div>

        @if (Model.Count == 0)
        {
            <div class="col-md-12 alert alert-danger text-center" style="font-size: 1.25em">
                @ViewBag.Message
            </div>
        }
        else
        {
            <table class="table">
                <tr>
                    <th>Movie Cover</th>
                    <th>Quantity</th>
                    <th>Title</th>
                    <th>Price</th>
                    <th>Total</th>
                    <th></th>
                </tr>
                @foreach (var item in Model)
                {
                    //when calling on an item in a dictionary, you have to specify KEY or VALUE
                    <tr>
                        <td style="vertical-align: middle">
                            <img src="~/Content/img/MoviesTV/t_@item.Value.Product.TitleImage" alt="Movie Cover" title="@item.Value.Product.Title" />
                        </td>
                        <td style="vertical-align: middle">
                            @* Provide a space for the user to update the qty *@
                            @using (Html.BeginForm("UpdateCart", "ShoppingCart", FormMethod.Post))
                            {
                                @Html.Hidden("movieTVID", item.Value.Product.MovieTVID)
                                @Html.TextBox("qty", item.Value.Qty, new { @class = "form-control", @style = "max-width: 50px; display: inline;" })
                                <input type="submit" value="Update Quantity" class="btn btn-danger" />
                            }
                            @{
                                //calculate the running total number of items in the cart
                                totalCountOfItems += item.Value.Qty;
                            }
                        </td>
                        <td style="vertical-align: middle">
                            @item.Value.Product.Title
                        </td>
                        <td style="vertical-align: middle">
                            @string.Format($"{item.Value.Product.Price:c}")
                        </td>
                        <td style="vertical-align: middle">
                            @* calculate lineTotal & update the running total variable for each row *@
                            @{
                                decimal? lineTotal = item.Value.Product.Price * item.Value.Qty;
                                cartTotal += lineTotal;
                            }
                            @string.Format($"{lineTotal:c}")
                        </td>
                        <td style="vertical-align: middle">
                            @* remove from cart functionality *@
                            @Html.ActionLink("Remove from Cart", "RemoveFromCart", "ShoppingCart", new { id = item.Value.Product.MovieTVID }, new { @class = "btn btn-danger" })
                        </td>
                    </tr>
                }
            </table>
            <p class="alert alert-danger text-center" style="font-size: 1.25em">
                You have @totalCountOfItems item@(totalCountOfItems > 1 ? "s" : "") in your cart. Your total before taxes and shipping is @string.Format($"{cartTotal:c}")
                @Html.ActionLink("Proceed to Checkout", "Checkout", "ShoppingCart", null, new { @class = "primary-btn cta-btn", style = "font-size: .75em; margin-left: 75px" })
            </p>
        }
    </div>
</div>