StoreFront.UI.MVC/Controllers/TitleStatusController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using StoreFront.DATA.EF;

namespace StoreFront.UI.MVC.Controllers
{
    public class TitleStatusController : Controller
    {
        private StoreFrontEntities db = new StoreFrontEntities();

        // GET: TitleStatus
        public ActionResult Index()
        {
            return View(db.TitleStatuses.ToList());
        }

        // GET: TitleStatus/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TitleStatus titleStatus = db.TitleStatuses.Find(id);
            if (titleStatus == null)
            {
                return HttpNotFound();
            }
            return View(titleStatus);
        }

        // GET: TitleStatus/Create
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: TitleStatus/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult Create([Bind(Include = "TitleStatusID,TitleStatusName,Notes")] TitleStatus titleStatus)
        {
            if (ModelState.IsValid)
            {
                db.TitleStatuses.Add(titleStatus);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(titleStatus);
        }

        // GET: TitleStatus/Edit/5
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TitleStatus titleStatus = db.TitleStatuses.Find(id);
            if (titleStatus == null)
            {
                return HttpNotFound();
            }
            return View(titleStatus);
        }

        // POST: TitleStatus/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult Edit([Bind(Include = "TitleStatusID,TitleStatusName,Notes")] TitleStatus titleStatus)
        {
            if (ModelState.IsValid)
            {
                db.Entry(titleStatus).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(titleStatus);
        }

        // GET: TitleStatus/Delete/5
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TitleStatus titleStatus = db.TitleStatuses.Find(id);
            if (titleStatus == null)
            {
                return HttpNotFound();
            }
            return View(titleStatus);
        }

        // POST: TitleStatus/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult DeleteConfirmed(int id)
        {
            TitleStatus titleStatus = db.TitleStatuses.Find(id);
            db.TitleStatuses.Remove(titleStatus);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        #region AJAX CRUD
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public JsonResult AjaxCreate(TitleStatus titleStatus)
        {
            db.TitleStatuses.Add(titleStatus);
            db.SaveChanges();
            return Json(titleStatus);
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public PartialViewResult TitleStatusEdit(int id)
        {
            TitleStatus titleStatus = db.TitleStatuses.Find(id);
            return PartialView(titleStatus);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public JsonResult AjaxEdit(TitleStatus titleStatus)
        {
            db.Entry(titleStatus).State = EntityState.Modified;
            db.SaveChanges();
            return Json(titleStatus);
        }

        [AcceptVerbs(HttpVerbs.Post)]
        [Authorize(Roles = "Admin")]
        public JsonResult AjaxDelete(int id)
        {
            TitleStatus titleStatus = db.TitleStatuses.Find(id);
            db.TitleStatuses.Remove(titleStatus);
            db.SaveChanges();
            string confirmMessage = string.Format("Deleted title status '{0}' from database!", titleStatus.TitleStatusName);
            return Json(new { id = id, message = confirmMessage });
        }
        #endregion

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

StoreFront.UI.MVC/Views/TitleStatus/Create.cshtml
@model StoreFront.DATA.EF.TitleStatus

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>TitleStatus</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.TitleStatusName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TitleStatusName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TitleStatusName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Notes, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Notes, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Notes, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

StoreFront.UI.MVC/Views/TitleStatus/Delete.cshtml
@model StoreFront.DATA.EF.TitleStatus

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>TitleStatus</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TitleStatusName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TitleStatusName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Notes)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Notes)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

StoreFront.UI.MVC/Views/TitleStatus/Details.cshtml
@model StoreFront.DATA.EF.TitleStatus

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>TitleStatus</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TitleStatusName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TitleStatusName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Notes)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Notes)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.TitleStatusID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

StoreFront.UI.MVC/Views/TitleStatus/Edit.cshtml
@model StoreFront.DATA.EF.TitleStatus

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>TitleStatus</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.TitleStatusID)

        <div class="form-group">
            @Html.LabelFor(model => model.TitleStatusName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TitleStatusName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TitleStatusName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Notes, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Notes, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Notes, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

StoreFront.UI.MVC/Views/TitleStatus/Index.cshtml
@model IEnumerable<StoreFront.DATA.EF.TitleStatus>

@{
    ViewBag.Title = "Title Status Index";
}

<div class="container">
    <h2>@ViewBag.Title</h2>

    <p class="row">
        <button id="toggleTitleStatusCreate" class="btn btn-danger text-right pull-left">Add New</button>
    </p>
    <div id="TitleStatusCreate">
        @Html.Partial("TitleStatusCreate", new StoreFront.DATA.EF.TitleStatus())
    </div>
    <table class="table data-table table-striped" id="TitleStatusTable">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.TitleStatusName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Notes)
                </th>
                <th></th>
            </tr>
        </thead>

        <tbody>
            @foreach (var item in Model)
            {
                <tr id="TitleStatus-@item.TitleStatusID">
                    <td>
                        @Html.DisplayFor(modelItem => item.TitleStatusName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Notes)
                    </td>
                    <td>
                        <a href="" class="EditLink" id="@item.TitleStatusID">Edit</a> |
                        @Ajax.ActionLink("Delete", "AjaxDelete", "TitleStatus", new { id = item.TitleStatusID },
                            new AjaxOptions {
                                HttpMethod = "POST",
                                Confirm = $"Are you sure you want to delete {item.TitleStatusName} from title statuses?",
                                OnSuccess = "deleteConfirmed",
                                OnFailure = "deleteFailed"
                            })
                    </td>
                </tr>
            }
        </tbody>

    </table>
</div>

@section scripts{
    <script>
        $(document).ready(function () {
            $(".data-table").DataTable({
                "order": [[0, "asc"]]
                });
        });

        //****** AJAX DELETE ******//
        function deleteConfirmed(response, status, data) {
            //remove the row from the table onscreen
            var rowId = "#TitleStatus-" + response.id;
            $("#TitleStatusTable").find(rowId).remove();

            //display a status message (use AJAX response's message property)
            $("#MessageContent").html("<div class='alert alert-success'>" + response.message + "</div>");
        }
        function deleteFailed(response, status, data) {
            //display a status message
            $("#MessageContent").html("<div class='alert alert-danger'>Delete unsuccessful. Please try again.</div>");
        }

        //****** AJAX CREATE ******//
        $("#TitleStatusCreate").hide(); //starts us out with the create form being hidden
        $("#toggleTitleStatusCreate").click(function () {
            $("#TitleStatusCreate").toggle(); //flips the element between being shown or hidden from the user
        }); //end of click function

        $("#TitleStatusCreateForm").submit(function (e) {
            var formData = $(this).serializeArray(); //serialization is the process of turning information in a certain language (C#) into a JSON format
            console.log(formData);
            e.preventDefault(); //keeps the default functionality (page reload) from happening
            $.ajax({
                url: "/TitleStatus/AjaxCreate",
                type: "POST",
                data: formData,
                dataType: "json",
                error: function (e) {
                    $("#MessageContent").html("<div class='alert alert-danger'>There was a problem!</div>");
                },
                success: function (foo) {
                    $("#MessageContent").html("<div class='alert alert-success'>Record added!</div>");
                    $("#TitleStatusCreateForm")[0].reset();
                    $(function () {
                        var row = '<tr><td>' + foo.TitleStatusName + '</td>' +
                            '<td>' + foo.Notes + '</td>' +
                            '<td>Refresh to view options</td></tr>';
                        $("#TitleStatusesTable").append(row);
                    });
                }
            });
        });

        //****** AJAX EDIT ******
        var originalContent = null;
        $('a.EditLink').click(function (e) {
            e.preventDefault();
            var titleStatusID = $(this).attr('id');
            var row = $("#TitleStatus-" + titleStatusID).children();
            originalContent = {
                TitleStatusID: titleStatusID,
                TitleStatusName: row[0].innerText,
                Notes: row[1].innerText,
            };
            console.log(originalContent);
            $.get("/TitleStatus/TitleStatusEdit/" + titleStatusID,
                function (data) {
                    $("#TitleStatus-" + titleStatusID).replaceWith(
                        '<tr id="TitleStatus-' + titleStatusID + '"><td colspan="5">' + data + '</td></tr>'
                    );
                });
        });

        $(document).on("click", "#saveUpdate", function () {
            var formData = $("#TitleStatusEditForm").serializeArray();

            $('#MessageContent').html("<div class='alert alert-info'>Please Wait...</div>");

            $.ajax({
                url: "/TitleStatus/AjaxEdit",
                type: "POST",
                data: formData,
                dataType: "json",
                success: function (data) {
                    $('#MessageContent').html("<div class='alert alert-success'>Your Record was Successfully Updated!</div>");
                    $('#TitleStatusEditForm')[0].reset();

                    $(function () {
                        var row = '<tr><td>' + data.TitleStatusName +
                            '</td><td>' + data.Notes +
                            '</td><td>Refresh to view options</td></tr>';

                        $('#TitleStatus-' + data.TitleStatusID).replaceWith(row);
                    });
                },
                error: function (e) {
                    $('#MessageContent').html("<div class='alert alert-warning'>There was an error. Please try again or contact the site administrator.</div>");
                    $(function () {
                        var row = '<tr id="TitleStatus-' + originalContent.TitleStatusID + '"> <td>' + originalContent.TitleStatusName +
                            '</td><td>' + originalContent.Notes +
                            '</td><td>Refresh to view options</td></tr>';

                        $('#TitleStatus-' + data.TitleStatusID).replaceWith(row);
                    });
                }
            });
        });
    </script>
}

StoreFront.UI.MVC/Views/TitleStatus/TitleStatusCreate.cshtml
@model StoreFront.DATA.EF.TitleStatus

@using (Html.BeginForm("", "", FormMethod.Post, new { id = "TitleStatusCreateForm" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <div class="col-md-3">
                @Html.EditorFor(model => model.TitleStatusName, new { htmlAttributes = new { @class = "form-control", placeholder = "Title Status" } })
                @Html.ValidationMessageFor(model => model.TitleStatusName, "", new { @class = "text-danger" })
            </div>

            <div class="col-md-6">
                @Html.EditorFor(model => model.Notes, new { htmlAttributes = new { @class = "form-control", placeholder = "Notes" } })
                @Html.ValidationMessageFor(model => model.Notes, "", new { @class = "text-danger" })
            </div>
            <div class="col-md-1">
                <input type="submit" value="Create" class="btn btn-danger" />
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

StoreFront.UI.MVC/Views/TitleStatus/TitleStatusEdit.cshtml
@model StoreFront.DATA.EF.TitleStatus

@using (Html.BeginForm("AjaxEdit", "TitleStatuses", FormMethod.Post, new { id = "TitleStatusEditForm" }))
{
    @Html.AntiForgeryToken()
    <table>
        <tr>
            @Html.HiddenFor(model => model.TitleStatusID)
            <td>
                @Html.EditorFor(model => model.TitleStatusName, new { htmlAttributes = new { @class = "form-control", style = "width:135px; margin-left:-10px; margin-right:10px;" } })
                @Html.ValidationMessageFor(model => model.TitleStatusName, "", new { @class = "text-danger" })
            </td>
            <td>
                @Html.EditorFor(model => model.Notes, new { htmlAttributes = new { @class = "form-control", style = "width:750px; margin-right:10px;" } })
                @Html.ValidationMessageFor(model => model.Notes, "", new { @class = "text-danger" })
            </td>
            <td>
                <input type="button" id="saveUpdate" value="Update Title Status" class="btn btn-danger" />
            </td>
        </tr>
    </table>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}